name: Train in development and production environments

on: 
  push:
    branches: [ main ]

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment: 
      name: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set default resource group and workspace
      run: |
        az configure --defaults group=rg-mlops-hanna-lqEGuu3yriQ
        az configure --defaults workspace=mlw-mlops-hanna-lqEGuu3yriQ
    - name: Trigger Azure Machine Learning training job in dev
      run: |
        az ml job create --file src/job.yml --stream 

  production:
    needs: experiment
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set default resource group and workspace
      run: |
        az configure --defaults group=rg-mlops-hanna-lqEGuu3yriQ
        az configure --defaults workspace=mlw-mlops-hanna-lqEGuu3yriQ
    - name: Trigger Azure Machine Learning training job in prod
      run: |
        az ml job create --file src/job_prod.yml --stream
