name: Deploy model to online endpoint

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set default resource group and workspace
      run: |
        az configure --defaults group=rg-mlops-hanna-lqEGuu3yriQ
        az configure --defaults workspace=mlw-mlops-hanna-lqEGuu3yriQ
    - name: Create online endpoint
      run: |
        az ml online-endpoint create --file src/online_endpoint.yml
    - name: Deploy model to online endpoint
      run: |
        az ml online-deployment create --file src/online_deployment.yml
